const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Plugins.Arr,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{anasayfa_zemin2: 0},
	{Tween: 0},
	{Sine: 0},
	{giris_btn: 0},
	{anasayfa_zemin: 0},
	{baslik: 0},
	{hazir: 0},
	{zemin: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{bakir: 0},
	{gumus: 0},
	{altin: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Varlık: 0},
	{Varlık2: 0},
	{soru_numaralari: 0},
	{soru_t_x: 0},
	{soru_t_y: 0},
	{soru_tablosu: 0},
	{dogru: 0},
	{yanlis: 0},
	{Flash: 0},
	{dogru2: 0},
	{yanlis2: 0},
	{soru_sira: 0},
	{element_kaplama: 0},
	{Sprite6: 0},
	{hidrojen: 0},
	{Pin: 0},
	{yanlis_pin: 0},
	{dogru_pin: 0},
	{Touch: 0},
	{Sprite: 0},
	{hak: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Mouse: 0},
	{bakir2: 0},
	{gumus2: 0},
	{altin2: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{anasayfa: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Varlık3: 0},
	{Varlık4: 0},
	{Varlık5: 0},
	{Varlık6: 0},
	{Varlık7: 0},
	{Varlık8: 0},
	{Varlık9: 0},
	{Varlık10: 0},
	{Varlık11: 0},
	{Varlık12: 0},
	{Varlık13: 0},
	{Varlık14: 0},
	{Varlık15: 0},
	{Varlık16: 0},
	{Varlık17: 0},
	{Varlık18: 0},
	{Varlık19: 0},
	{Varlık20: 0},
	{Varlık21: 0},
	{Varlık22: 0},
	{Varlık23: 0},
	{Varlık24: 0},
	{Varlık25: 0},
	{Varlık26: 0},
	{Varlık27: 0},
	{Varlık28: 0},
	{Varlık29: 0},
	{Varlık30: 0},
	{Varlık31: 0},
	{Varlık32: 0},
	{Varlık33: 0},
	{Varlık34: 0},
	{Sprite15: 0},
	{Sprite7: 0},
	{kazanilan_el: 0},
	{Audio: 0},
	{Browser: 0},
	{Text: 0},
	{Varlık35: 0},
	{kaynakca: 0},
	{kutuphane: 0},
	{dogruyanlis: 0},
	{sira: 0},
	{sec1x: 0},
	{sec1y: 0},
	{sec2y: 0},
	{sec2x: 0},
	{sec_eski_y: 0},
	{tablo_eski_y: 0},
	{sec_sira: 0},
	{yanlis_sayisi: 0},
	{soru_sayisi: 0}
];

self.InstanceType = {
	anasayfa_zemin2: class extends self.ISpriteInstance {},
	giris_btn: class extends self.ISpriteInstance {},
	anasayfa_zemin: class extends self.ISpriteInstance {},
	baslik: class extends self.ISpriteInstance {},
	hazir: class extends self.ISpriteInstance {},
	zemin: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	bakir: class extends self.ISpriteInstance {},
	gumus: class extends self.ISpriteInstance {},
	altin: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Varlık: class extends self.ISpriteInstance {},
	Varlık2: class extends self.ISpriteInstance {},
	soru_numaralari: class extends self.ISpriteInstance {},
	soru_tablosu: class extends self.ISpriteInstance {},
	dogru: class extends self.ISpriteInstance {},
	yanlis: class extends self.ISpriteInstance {},
	dogru2: class extends self.ISpriteInstance {},
	yanlis2: class extends self.ISpriteInstance {},
	soru_sira: class extends self.IArrayInstance {},
	element_kaplama: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	hidrojen: class extends self.ISpriteInstance {},
	yanlis_pin: class extends self.ISpriteInstance {},
	dogru_pin: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	hak: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bakir2: class extends self.ISpriteInstance {},
	gumus2: class extends self.ISpriteInstance {},
	altin2: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	anasayfa: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Varlık3: class extends self.ISpriteInstance {},
	Varlık4: class extends self.ISpriteInstance {},
	Varlık5: class extends self.ISpriteInstance {},
	Varlık6: class extends self.ISpriteInstance {},
	Varlık7: class extends self.ISpriteInstance {},
	Varlık8: class extends self.ISpriteInstance {},
	Varlık9: class extends self.ISpriteInstance {},
	Varlık10: class extends self.ISpriteInstance {},
	Varlık11: class extends self.ISpriteInstance {},
	Varlık12: class extends self.ISpriteInstance {},
	Varlık13: class extends self.ISpriteInstance {},
	Varlık14: class extends self.ISpriteInstance {},
	Varlık15: class extends self.ISpriteInstance {},
	Varlık16: class extends self.ISpriteInstance {},
	Varlık17: class extends self.ISpriteInstance {},
	Varlık18: class extends self.ISpriteInstance {},
	Varlık19: class extends self.ISpriteInstance {},
	Varlık20: class extends self.ISpriteInstance {},
	Varlık21: class extends self.ISpriteInstance {},
	Varlık22: class extends self.ISpriteInstance {},
	Varlık23: class extends self.ISpriteInstance {},
	Varlık24: class extends self.ISpriteInstance {},
	Varlık25: class extends self.ISpriteInstance {},
	Varlık26: class extends self.ISpriteInstance {},
	Varlık27: class extends self.ISpriteInstance {},
	Varlık28: class extends self.ISpriteInstance {},
	Varlık29: class extends self.ISpriteInstance {},
	Varlık30: class extends self.ISpriteInstance {},
	Varlık31: class extends self.ISpriteInstance {},
	Varlık32: class extends self.ISpriteInstance {},
	Varlık33: class extends self.ISpriteInstance {},
	Varlık34: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	kazanilan_el: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Varlık35: class extends self.ISpriteInstance {},
	kaynakca: class extends self.ISpriteInstance {},
	kutuphane: class extends self.ISpriteInstance {},
	dogruyanlis: class extends self.ISpriteInstance {}
}